apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik-base
  namespace: traefik-system

spec:
  prune: true
  interval: 30m
  timeout: 2m

  targetNamespace: traefik-system
  path: ./core/traefik/base/

  patches:
    - patch: |-
        - op: replace
          path: /data/values.yaml
          value: |-
            deployment:
              replicas: 1
        
            additionalArguments:
              - "--providers.kubernetesingress.ingressclass=traefik"

            service:
              enabled: true
              type: LoadBalancer
              annotations:
                metallb.universe.tf/address-pool: public-pool
              spec:
                loadBalancerIP: 192.168.100.245
        
            
            logs:
              general:
                level: INFO
                filePath: "/var/log/traefik.log"
            
            providers:
              kubernetesCRD:
                allowCrossNamespace: true

      target:
        kind: ConfigMap
        name: traefik-helm-values
        namespace: traefik-system

  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system