apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ceph-overlays
  namespace: ceph-csi

spec:
  prune: true
  interval: 30m
  timeout: 2m

  targetNamespace: ceph-csi
  path: ./core/ceph/overlays/k
  dependsOn:
    - name: ceph-base

  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
