apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: csi-rbd-secret
  namespace: ceph-csi
spec:
  encryptedData:
    userID: AgCi6ykW5o+QmBt91C4ktPCzqjEQEZh4U58pjYHVifUG7RWjSxrSUN3p+PwmptB3jhuf/Z9TbnR/Jgj7nxYXFnPNLk14ayr6TjtAVjwbncdkld+ZHyKrqovdLdDQ1Infp8bqoBMfBupqaXEb60zz17wJi92iDx9t9eUhm8nT79XLbDsf+qxBdILZukXYdcCBVaj2UFNLKSm4rmunHTI1LC5Cvr668W+Vt82f4GhmdLF8Qxp3f6CAtRVxZIAAgQT4u+FpE++kokxTlLyWSbEhDVb8rEAShVIyB9Lv/fMXvwpLqCY3KHX8dfb932zjdvmbIbjQbYlnmTyHU+a+wIeEGHuQgv4vN8n2DlveKQHiZRMBYF2o4f3uRurA5Ch6WPD0BaqpIq3EjQaKe3CWxtf8/3+R1OMGSw57AzWC2X8aE19N0SXSJo+58pKwgDT3uzrrTy8t16LtAiTUUfdP2N2GN2mac8y/AD738IRNSAZJ75eEU70/g2HG2sjxs/OcUmFyiO4MCvm/o3KCHSpPUKMcsmf0W6D9XVbCZWrvy71J+4xaEegZYV6V2SIb5hEEbn+FEfAfVQG6snoGgNlPSosL2GAIks8fkLLJ6ycQ5hhXAjdAyXavi5HtjQxfBTsp7W2mIKHqrqeDJrNUtbm0qRE1yEKcJGkA+WBcLCeobN15Y4q6vTto69YMOqQegJ6kvk6lU7ONK3xR1S+niL5w2qpjnQ==
    userKey: AgB3Fjcjhb4YEglE3rvOYNkssE7o58DuRfHybNSPBr78dI68Io8oMGXc/nvAARxsTW5dcvvU7k54GHoAAfRb+EZjywtukioR4AB+xBS2ZjrD28Pr53SzQqB/6xWuA4SByA67aPuk5SEfrUlhRlXKsSFgDAwWybmjZBAyTYfdhUitOm/g8hOa/5gv95Fl4+b/poRnuWaB6k1z+udxRqItAdf1+MmDdF4LkK2HIQEs4IApwV1luXAI3bkYMJxCmV/0N6pXKyor3b4M+NccahBROoAF47S+P4YnTWKbRwcBGBd7skNj2+MF5T+aHCr5ywppTqyityQzo8YzX9eHSou7+//VthD0y99qTbwoJp6zyV5PdfwyobzEtl2kWOymw+/EM8HNUfgaIX5ZNDrp1v4iPZtvuKOMvP3c7ZhNDPP51TAsrSQLvMB3ihfrn5FuQVDkRYsdlAITXFFMRSNYQp9K6kaM7N49XUrHGTJZMZL7kat9pZbipvIgGLhAfLfkxWeaIjYtCGESvWeSMdjQSaTRs9Nt8QKKcHZzKRPubFtKqIJwKuC729H73r4Yxo+h2dVqd92PsSj8WppqKnjn6IUsZombJ/fgmUHTKAM1cpxwDBxeaTrOy09BQ7CaP3C9zDALO99XRTVali8HQo8qbMZkko1qYpD4o89ahXYzoe5zBHpA0Rc48M3wZk40ZwReoYDtZWZQDeQWnKhtT2Qi0hnyFnoIW4pQ15wgoU8KqR5JMpc859o5U3XprZZO
  template:
    metadata:
      creationTimestamp: null
      name: csi-rbd-secret
      namespace: ceph-csi
