apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-overlays
  namespace: metallb-system

spec:
  prune: true
  interval: 30m
  timeout: 2m

  targetNamespace: metallb-system
  path: ./core/metallb-system/overlays/k
  dependsOn:
    - name: metallb-base

  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system