apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-output
  namespace: fluentd
data:
  fluentd.conf: |
    <source>
      @type forward
      bind 0.0.0.0
      port 24224
    </source>

    <source>
      @type http
      bind 0.0.0.0
      port 9880
    </source>
    
    <source>
      @type tail      
      path /var/log/pods/*
   
      tag kubernetes.*
      exclude_path ["/var/log/pods/fluent*"]
      read_from_head true
      <parse>
        @type regexp
        expression /^(?<time>.+) (?<stream>stdout|stderr)( (?<logtag>.))? (?<log>.*)$/
      </parse>
   
    </source> 

    <match **>
      @type elasticsearch
      include_tag_key true
      host elastic-elasticsearch.elastic-system
      port 9200
      scheme https
      user elastic
      password ts2PwaAo60hPPnEx
      logstash_format true
      logstash_prefix xxx
    
      ssl_verify false
      ssl_version TLSv1_2
   

      <buffer>
        @type file
        path /opt/bitnami/fluentd/logs/buffers/logs.buffer
        flush_thread_count 2
        flush_interval 5s
      </buffer>
    </match>
