apiVersion: v1
kind: ConfigMap
metadata:
  name: elastic-ca-crt
  namespace: fluetnd
data:
  ca_crt.pem: |
    -----BEGIN CERTIFICATE-----
    MIIDIjCCAgqgAwIBAgIRAMFBRqhLvpuItVegfB7pdZ8wDQYJKoZIhvcNAQELBQAw
    GzEZMBcGA1UEAxMQZWxhc3RpY3NlYXJjaC1jYTAeFw0yNDAzMTcwOTMxMDJaFw0y
    NTAzMTcwOTMxMDJaMBsxGTAXBgNVBAMTEGVsYXN0aWNzZWFyY2gtY2EwggEiMA0G
    CSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDZFcBuS1+bNjoP4y2KF2kSTq3UxorC
    61TRp7NGHvxDfge7FV/+hw3+gCBgnGbMRvjvegVQXl+1G1tXlNUq7c4gPiEy5Zbv
    c+ygV8KbTxbl3ysG4ARKCF2M9Qgjhb5zoIMofNWVAoM67GyqoeX8JQztRzrEbg4u
    +ZbsOPgtsDfOHWs/kC/64w82QHNiQClLmr5o9N7ogHwuqycaXtAh/onR582op/oh
    vmdLAJsqdmXgBaZE4QvAZsuS53COAUrVBetXxUfK3U7ilnp8Y9BCyUyes8C4SF1z
    jzD/T7QhPPi9OcAJXSLQCGKpx3Jgm5BatITauOoMth4G1MTkqKa8e7pzAgMBAAGj
    YTBfMA4GA1UdDwEB/wQEAwICpDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUH
    AwIwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUAydRZXQgd7uAyu5ThL2Rf+UI
    H2gwDQYJKoZIhvcNAQELBQADggEBAFuigAzSzgXnAM5BPMuGmv+1GC+ALKWWMtBr
    wZgZN0zipzQhCNYDyK7HrlTXl04gw2cdFcFDnlIT2b12vEvUas0kToVJqF7zRbOn
    0Kx3km+1+Ir0CSwPpa5zU6ogTLHGX51NPNWupsCAr0/G1vdSRW3XoZ4mWD4cmYde
    RgRokwB6qRK9OHBmbyLOARifRKt06Mns8GDXhsN+BPm6IQz6Op0+wINpcLq/5VPy
    lFEmxFxwPkbJaW4XEvWSiuMXCKG/HCVsyLR3IRc7TD9y8oeJyKF0xvCch4gsJBe2
    6YpsDrfvYwIoafU4o3HiBeU+YHYqUk6uqhtl3shyZAvrqKwI92g=
    -----END CERTIFICATE-----
