apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-helm-values
  namespace: fluentd
data:
  values.yaml: |
    global:
      storageClass: nfs
    aggregator:
      configMap: elasticsearch-output
      extraGems:
        - fluent-plugin-parser-cri
      extraEnvVars: 
        #these do not seem to work
        - name: ELASTICSEARCH_HOST
          value: elastic-elasticsearch.elastic-system
        - name: ELASTICSEARCH_PORT
          value: "9200"





