apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fluent
  namespace: fluentd
spec:
  interval: 4h
  timeout: 1m

  chart:
    spec:
      chart: fluentd
      version: 1.16.3
      sourceRef:
        kind: HelmRepository
        name: bitnami-oci
        namespace: flux-system

  valuesFrom:
    - kind: ConfigMap
      name: fluentd-helm-values
      valuesKey: values.yaml
