apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-nginx
  namespace: test
  # this is a trivial deployment to check if flux and kustomizations work
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-nginx

  template:
    metadata:
      labels:
        app: test-nginx
    spec:
      containers:
      - name: test-nginx
        image: nginx:1-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
