apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ceph-csi
  namespace: ceph-csi
spec:
  interval: 4h
  timeout: 1m

  chart:
    spec:
      chart: ceph-csi-rbd
      version: 3.8.0
      sourceRef:
        kind: HelmRepository
        name: ceph-csi
        namespace: flux-system

  valuesFrom:
    - kind: ConfigMap
      name: ceph-helm-values
      valuesKey: values.yaml
