apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: secret-generator
  namespace: secret-generator

spec:
  prune: true
  interval: 30m
  timeout: 2m

  targetNamespace: secret-generator
  path: ./core/secret-generator/

  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
