apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sealed-secrets
  namespace: sealed-secrets

spec:
  prune: true
  interval: 30m
  timeout: 2m

  targetNamespace: sealed-secrets
  path: "./core/sealed-secrets/base/"


  patches:
    - patch: |-
        - op: replace
          path: /data/values.yaml
          value: |-
            gg: 2
      target:
        kind: ConfigMap
        name: ss
        namespace: sealed-secrets

  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
