apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: elastic-base
  namespace: elastic-system

spec:
  prune: true
  interval: 30m
  timeout: 2m

  targetNamespace: elastic-system
  path: ./core/elasticsearch/base/

  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
