apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: secret-generator
  namespace: secret-generator
spec:
  interval: 4h
  timeout: 1m

  chart:
    spec:
      chart: kubernetes-secret-generator
      version: 3.4.0
      sourceRef:
        kind: HelmRepository
        name: mittwald
        namespace: flux-system

  valuesFrom:
    - kind: ConfigMap
      name: secret-generator-chart-values
      valuesKey: values.yaml
