apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nfs
  namespace: flux-system
spec:
  interval: 4h
  url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
