apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nfs-base
  namespace: nfs

spec:
  prune: true
  interval: 30m
  timeout: 2m

  targetNamespace: nfs
  path: ./core/nfs/base/

  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
