apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: smoke-api
  namespace: smoke
spec:
  interval: 15m
  timeout: 1m
  chart:
    spec:
      chart: app-chart
      version: 1.0.11
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: flux-system
  values:
    app:
      replicas: 2
      image:
        repository: wsiz/smoke
        tag: 0.1.1
      service:
        targetPort: 5000
    certificate:
      commonName: "smoke.wsi.edu.pl"
      issuer:
        name: letsencrypt-prod
        kind: ClusterIssuer
    ingressRoute:
      domain: smoke.wsi.edu.pl
      middlewares:
        - name: headers-middleware
        - name: ratelimit-middleware
    database:
      enabled: true
      database: smokedb
      image:
        tag: 16-alpine
      storage:
        storageClassName: ceph-wrong
        resources:
          requests:
            storage: 256Mi
      backups:
        storageClassName: ceph-wrong
        schedule: "0 12 * * *"
        resources:
          requests:
            storage: 256Mi
