apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik-system
spec:
  interval: 4h
  timeout: 1m

  chart:
    spec:
      chart: traefik
      version: 21.2.0
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system

  valuesFrom:
    - kind: ConfigMap
      name: traefik-helm-values
      valuesKey: values.yaml