apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-helm-values
  namespace: traefik-system
data:
  values.yaml: |
    deployment:
      replicas: 2
    
    providers:
      kubernetesCRD:
        allowCrossNamespace: true