apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: sealed-secrets
spec:
  interval: 4h
  timeout: 1m

  chart:
    spec:
      chart: sealed-secrets
      version: 2.7.6  # consider upgrade to 2.14.2
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: flux-system

  valuesFrom:
    - kind: ConfigMap
      name: sealed-secrets-chart-values
      valuesKey: values.yaml
