apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 4h
  timeout: 1m

  chart:
    spec:
      chart: cert-manager
      version: 1.11.0
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system

  valuesFrom:
    - kind: ConfigMap
      name: cm-helm-values
      valuesKey: values.yaml
