apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fluentd-base
  namespace: fluent

spec:
  prune: true
  interval: 30m
  timeout: 2m

  targetNamespace: fluent
  path: ./core/fluent/base/

  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
