apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cm-base
  namespace: cert-manager

spec:
  prune: true
  interval: 30m
  timeout: 2m

  targetNamespace: cert-manager
  path: ./core/cert-manager/base/

  patches:
    - patch: |-
        - op: replace
          path: /data/values.yaml
          value: |-
            installCRDs: true

#            prometheus:
#              enabled: true
#              servicemonitor:
#                enabled: true
#                labels:
#                  release: prometheus-stack

      target:
        kind: ConfigMap
        name: cm-helm-values
        namespace: cert-manager

  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
