apiVersion: v1
kind: ConfigMap
metadata:
  name: elastic-helm-values
  namespace: elastic-system
data:
  values.yaml: |
    global:
      storageClass: ceph-wrong
    master:
      masterOnly: false
      replicaCount:1
      heapSize: 800m