apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elastic
  namespace: elastic-system
spec:
  interval: 4h
  timeout: 1m

  chart:
    spec:
      chart: elasticsearch
      version: 19.21.1
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system

  valuesFrom:
    - kind: ConfigMap
      name: elastic-helm-values
      valuesKey: values.yaml
