apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kibana-tls-cert
  namespace: elastic-system
spec:
  commonName: "kibana-test.wsi.edu.pl"
  secretName: tls-cert

  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer

  dnsNames:
    - "kibana-test.wsi.edu.pl"
