apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  releaseName: metallb

  interval: 4h
  timeout: 1m

  chart:
    spec:
      chart: metallb
      version: 4.1.20
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system

  valuesFrom:
    - kind: ConfigMap
      name: metallb-chart-values
      valuesKey: values.yaml