apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-helm-values
  namespace: fluentd
data:
  values.yaml: |
    config:
      customParsers: |
        [PARSER]
            Name docker_no_time
            Format json
            Time_Keep Off
            Time_Key time
            Time_Format %Y-%m-%dT%H:%M:%S.%L
    
        [PARSER]
            Name loguru
            Format regex
            Regex ^(?<atimestamp>[^\|]+) \| (?<loglevel>[^ ]+) *. (?<file>[^:]+):(?<function>[^:]+):(?<line>[^ ]+) - (?<msg>.+)$

      filters: |
        [FILTER]
            Name kubernetes
            Match kube.*
            Merge_Log On
            Keep_Log Off
            K8S-Logging.Parser On
            K8S-Logging.Exclude On
        
        [FILTER]
            Name pythonapp
            Match kube.*smoke*
            Key_Name log
            Parser docker_no_time

      outputs: |
        [OUTPUT]
            Name es
            Match kube.*
            Host elastic-elasticsearch.elastic-system
            Port 9200
            HTTP_User       elastic
            HTTP_Passwd     ts2PwaAo60hPPnEx
            Logstash_Format On
            Logstash_Prefix yyyy
            Suppress_Type_Name On
            Replace_Dots On
            Type _doc
            Retry_Limit False
            tls On
            tls.verify Off
    
        [OUTPUT]
            Name es
            Match host.*
            Host elastic-elasticsearch.elastic-system
            Port 9200
            HTTP_User       elastic
            HTTP_Passwd     ts2PwaAo60hPPnEx
            Logstash_Format On
            Logstash_Prefix yyyy-node
            Suppress_Type_Name On
            Replace_Dots On
            Type _doc
            Retry_Limit False
            tls On
            tls.verify Off




