apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fluent
  namespace: fluent
spec:
  interval: 4h
  timeout: 1m

  chart:
    spec:
      chart: fluent-bit
      version: 0.44.0
      sourceRef:
        kind: HelmRepository
        name: fluent
        namespace: flux-system

  valuesFrom:
    - kind: ConfigMap
      name: fluentd-helm-values
      valuesKey: values.yaml
