apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs
  namespace: nfs
spec:
  interval: 4h
  timeout: 1m

  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: 4.0.18
      sourceRef:
        kind: HelmRepository
        name: nfs
        namespace: flux-system

  valuesFrom:
    - kind: ConfigMap
      name: nfs-helm-values
      valuesKey: values.yaml
