apiVersion: v1
kind: ConfigMap
metadata:
  name: nfs-helm-values
  namespace: nfs
data:
  values.yaml: |
    nfs:
      server: 192.168.100.83
      path: /sobol/nfs
    
    storageClass:
      name: nfs
      defaultClass: false
      allowVolumeExpansion: true
      reclaimPolicy: Delete
      accessModes: ReadWriteOnce
