apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: smoke
  namespace: smoke

spec:
  prune: true
  interval: 30m
  timeout: 2m

  targetNamespace: smoke
  path: ./apps/smoke/prod/

  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
